# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0004_auto_20170829_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='real_name',
        ),
    ]
