# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0005_remove_profile_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.TextField()),
                ('hash_md5', models.CharField(max_length=47)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='userDB.Profile')),
            ],
        ),
    ]
