# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0006_sshkey'),
        ('userDB', '0006_macaddress'),
    ]

    operations = [
    ]
