# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0007_merge_20180304_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='sshkey',
            options={'ordering': ['hash_md5'], 'verbose_name': 'SSH key', 'verbose_name_plural': 'SSH keys'},
        ),
        migrations.RemoveField(
            model_name='macaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='macaddress',
            name='profile',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='mac_address', to='userDB.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.BooleanField(default=False, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveSmallIntegerField(help_text='Will be automatically generated if user is set as member', null=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='hash_md5',
            field=models.CharField(help_text='Automatically generated hash of the key', max_length=47, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='key',
            field=models.TextField(verbose_name='SSH key'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
