# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0008_auto_20180305_0022'),
        ('userDB', '0008_auto_20180305_0035'),
    ]

    operations = [
    ]
