# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import userDB.models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0010_merge_20180305_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macaddress',
            options={'ordering': ['profile__user__username'], 'verbose_name': 'MAC address', 'verbose_name_plural': 'MAC addresses'},
        ),
        migrations.AddField(
            model_name='macaddress',
            name='vendor',
            field=models.CharField(default='beep', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macaddress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_addresses', to='userDB.Profile'),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='key',
            field=models.TextField(validators=[userDB.models.ssh_key_validator], verbose_name='SSH key'),
        ),
    ]
