# Generated by Django 2.1.7 on 2019-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0011_auto_20180318_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.BooleanField(blank=True, default=False, verbose_name='Member'),
        ),
    ]
